# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer
  colorscheme = "space-vim-dark"
  colorscheme_bg = "dark"
  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_iseparator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  relativenumber = false
  filemanager = "nerdtree"
  filetree_direction = "left"
  default_indent = 2
  bootstrap_after = 'myspacevim#before'

# Disable unwanted layers
[[layers]]
  name = 'core#statusline'
  enable = false

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto_completion_return_key_behavior = "complete"
  auto_completion_tab_key_behavior = "smart"
[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30
  default_shell = 'terminal'

[[layers]]
  name = 'colorscheme'
[[layers]]
  name = 'format'
[[layers]]
  name = 'incsearch'
# [[layers]]
#   name = "denite"
[[layers]]
    name = 'git'
[[layers]]
    name = 'VersionControl'

# Language supports
[[layers]]
  name = 'lang#elixir'
[[layers]]
  name = "lang#nix"
[[layers]]
  name = "tmux"

# Custom Plugins
[[custom_plugins]]
repo = "https://github.com/liuchengxu/space-vim-dark.git"
merged = 0
[[custom_plugins]]
repo = "https://github.com/vim-airline/vim-airline.git"
merged = 0
[[custom_plugins]]
repo = "https://github.com/vim-airline/vim-airline-themes.git"
merged = 0
[[custom_plugins]]
repo = "https://github.com/frazrepo/vim-rainbow.git"
merged = 0

