e.=explorer .
ls=ls --show-control-chars -F --color $*
pwd=cd
clear=cls
history=cat %CMDER_ROOT%\config\.history
unalias=alias /d $1
gl=git log --decorate --oneline --graph  
gs=git status -s -b  
bfg=java -jar C:\Libs\Git\BFG\bfg-1.12.13.jar $*  
